#ifndef _LIBDEFINES_H
#define _LIBDEFINES_H


#define MAX_BOOKS 1000
#define MAX_USERS 100
#define BOOK_TITLE_LENGTH 100
#define AUTHOR_NAME_LENGTH 100
#define USER_NAME_LENGTH 100
#define MAX_BOOK_BORROW 100

typedef enum {
	BOOK_STATUS_AVAILABLE,
	BOOK_STATUS_BORROWED
} BookStatus;

#define CODE_SUCCESS 0
#define CODE_ERROR_GENERIC -1
#define CODE_ERROR_NOT_FOUND -2
#define CODE_ERROR_ALREADY_EXISTS -3
#define CODE_ERROR_INVALID_INPUT -4
#define CODE_ERROR_CAPACITY_FULL -5
#define CODE_ERROR_BOOK_NOT_AVAILABLE -6
#define CODE_ERROR_USER_MAX_BOOKS_REACHED -7
#define CODE_ERROR_BOOK_NOT_BORROWED_BY_USER -8
#define CODE_ERROR_BOOK_BORROWED -9

#endif
