CC = GCC
AR = ar
RCS = rcs
CFLAGS = -Wall -Werror -std=c++11

CUR_DIR = .
SRC_DIR = $(CUR_DIR)/src
OBJ_DIR = $(CUR_DIR)/obj
LIB_DIR = $(CUR_DIR)/lib
INC_DIR = $(CUR_DIR)/inc
BIN_DIR = $(CUR_DIR)/bin

